=== FranDLP/lmsgi24/UT3/XSD/UT3_A05/Biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elemento raÃ­z -->
    <xs:element name="catalogo">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="fecha" type="xs:date"/>
        <xs:element name="autores">
        <xs:complexType>
    <xs:sequence>
        <xs:element name="autor" maxOccurs="unbounded">
    <xs:complexType>
    <xs:simpleContent>
        <xs:extension base="xs:string">
        <xs:attribute name="nombre" type="xs:string" use="required"/>
        <xs:attribute name="correo" type="xs:string" use="optional"/>
    </xs:extension>
    </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    </xs:sequence>
    </xs:complexType>
        </xs:element>
        <xs:element name="paginas" type="xs:int"/>
        <xs:element name="editorial" type="xs:string"/>
    </xs:sequence>
        <xs:attribute name="ISBN" type="xs:string" use="required"/>
    </xs:complexType>
    </xs:element>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    
</xs:schema>

=== FranDLP/lmsgi24/UT3/XSD/UT3_A05/Biblioteca CON XSD EXTERNO.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Biblioteca.xsd">
    <libro ISBN="978-3-16-148410-0">
        <titulo>Microsoft quiere comerse a Slack</titulo>
        <fecha>2020-01-05</fecha>
        <numLectores>25000</numLectores>
        <autores>
            <autor nombre="Pedro Picapiedra" mail="jimenez@aruario.es"/>
            <autor nombre="Alonso Pérez" mail="rosamar@exterior.es"/>
        </autores>
    </libro>
    <libro ISBN="974-1-46-140010-5">
        <titulo>La ética de la Libertad</titulo>
        <fecha>2020-01-09</fecha>
        <numLectores>35000</numLectores>
        <autores>
            <autor nombre="Murray N. Rothbard" mail="murrayrothbard@editorial.es"/>
        </autores>
    </libro>
</catalogo>
